name: Optimize Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1'  # Every Monday 03:00 UTC weekly optimization sweep
  workflow_dispatch:      # Allow manual runs from the Actions tab

jobs:
  optimize-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Optimize images
        uses: calibreapp/image-actions@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnlyChanged: false  # Re-optimize ALL images each run (not just those changed in the PR)
